#!/bin/bash
set -e 

core_packages {
  apt-get install -y tmux vim tree atop git 
}

timl {
  git clone git@github.com:christophermlewis/timl.git
}

configs {
  ln -s timl/linux/.vimrc .
  ln -s timl/linux/.tmux.conf .
}

core_packages
timl
configs
