#!/bin/bash
set -e 

core_packages() {
  apt-get install -y tmux vim tree atop git 
}

timl() {
  git clone https://github.com/christophermlewis/timl.git
  cd timl
  git checkout vagrant
  cd -
}

configs() {
  ln -s timl/linux/.vimrc .
  ln -s timl/linux/.tmux.conf_old_syntax .tmux.conf
}

core_packages
timl
configs
